version: '3'

services:
  audio-processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_DEBUG=false
    env_file:
      - .env
    volumes:
      - ./credentials:/app/credentials
    restart: unless-stopped
